# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'API ImagShow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for API ImagShow
pod 'Alamofire'

  target 'API ImagShowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'API ImagShowUITests' do
    # Pods for testing
  end

end
